version: "3.7"

services: 
  creditoro_epg_poller:
    container_name: creditoro_epg_poller
    build: 
      context: .
      dockerfile: docker/Dockerfile
    command: mvn exec:java -D"exec.mainClass"="dk.creditoro.epg_poller.RunEPGPoller"
    networks:
      - web

networks:
  web:
    external:
      name: web
