# This test the code then it gets pushed to master og pull_request

name: Creditoro EPG-Poller unittests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with docker-compose and run unit test.
        run: |
          docker-compose up -d --build
          docker-compose exec -T creditoro_epg_poller mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tag-image:
      runs-on: ubuntu-latest
      needs: tests
      steps:
        - uses: actions/checkout@v2
        - name: Tag image
          run: |
            echo -n ${{ secrets.DOCKER_HUB_PASS }} | docker login -u creditoro --password-stdin
            docker build -t creditoro/epg:production -f docker/Dockerfile .
            docker push creditoro/epg:production
